function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 31-Aug-2023 13:08:11

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create ylabel
ylabel({'Acceleration (m/s^2)'});

% Create xlabel
xlabel({'Time'});

% Create title
title({'My Custom Plot'});

box(axes1,'on');
hold(axes1,'off');
