function practiceData = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PRACTICEDATA = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  PRACTICEDATA = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  practiceData = importfile("C:\Users\tkyung\Downloads\Quadcopter\Quadcopter_Updated\Data\practiceData.csv", [8, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 31-Aug-2023 13:06:35

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [8, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "modeNumber", "acc1", "acc2", "acc3", "angRate1", "angRate2", "angRate3", "batteryVolts", "motorCmds1", "motorCmds2", "motorCmds3", "motorCmds4", "pos1", "pos2", "pos3", "isBallFlag"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "time", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "time", "EmptyFieldRule", "auto");

% Import the data
practiceData = readtable(filename, opts);

end